"""
Landing Builder — Генерирует полный лендинг по blueprint + content + design_spec.
Создаёт HTML, CSS, JS, PHP handler, генерирует AI фото.
Выход: директория с файлами + build_report.json
"""
import json
import logging
import os
import re
from typing import Optional, Callable

logger = logging.getLogger(__name__)


def build_landing(
    blueprint: dict,
    content: dict,
    design_spec: dict,
    output_dir: str,
    generate_image_fn: Optional[Callable] = None,
    ssh_fn: Optional[Callable] = None,
) -> dict:
    """
    Генерирует полный лендинг.
    
    Args:
        blueprint: site_blueprint.json
        content: site_content.json (тексты для каждой секции)
        design_spec: site_design_spec.json
        output_dir: Директория для сохранения файлов
        generate_image_fn: Функция генерации AI-фото (prompt -> url)
        ssh_fn: Функция SSH для деплоя на сервер
    
    Returns:
        dict: build_report с результатами
    """
    os.makedirs(output_dir, exist_ok=True)
    os.makedirs(os.path.join(output_dir, "images"), exist_ok=True)
    
    report = {
        "files_created": [],
        "photos_generated": 0,
        "photos_failed": 0,
        "errors": [],
        "status": "building",
    }
    
    colors = design_spec.get("colors", {})
    typography = design_spec.get("typography", {})
    fonts = design_spec.get("google_fonts", ["Inter"])
    
    # ── 1. Генерируем CSS ────────────────────────────────────
    css = _generate_css(blueprint, design_spec)
    css_path = os.path.join(output_dir, "style.css")
    with open(css_path, "w", encoding="utf-8") as f:
        f.write(css)
    report["files_created"].append("style.css")
    
    # ── 2. Генерируем JS ─────────────────────────────────────
    js = _generate_js(blueprint)
    js_path = os.path.join(output_dir, "main.js")
    with open(js_path, "w", encoding="utf-8") as f:
        f.write(js)
    report["files_created"].append("main.js")
    
    # ── 3. Генерируем PHP handler ────────────────────────────
    php = _generate_php_handler(blueprint)
    php_path = os.path.join(output_dir, "send.php")
    with open(php_path, "w", encoding="utf-8") as f:
        f.write(php)
    report["files_created"].append("send.php")
    
    # ── 4. Генерируем AI фото ────────────────────────────────
    photo_map = {}
    if generate_image_fn and blueprint.get("photo_prompts"):
        for pp in blueprint["photo_prompts"]:
            try:
                variant = pp.get("variant", 0)
                filename = f"{pp['section']}_{variant}.png" if variant else f"{pp['section']}.png"
                url = generate_image_fn(pp["prompt"])
                photo_map[filename] = url
                report["photos_generated"] += 1
                logger.info(f"[LandingBuilder] Photo generated: {filename}")
            except Exception as e:
                report["photos_failed"] += 1
                report["errors"].append(f"Photo {pp['section']}: {e}")
                logger.warning(f"[LandingBuilder] Photo failed: {pp['section']}: {e}")
    
    # ── 5. Генерируем HTML ───────────────────────────────────
    html = _generate_html(blueprint, content, design_spec, photo_map)
    html_path = os.path.join(output_dir, "index.html")
    with open(html_path, "w", encoding="utf-8") as f:
        f.write(html)
    report["files_created"].append("index.html")
    
    # ── 6. Privacy page ──────────────────────────────────────
    privacy = _generate_privacy_page(blueprint, design_spec)
    privacy_path = os.path.join(output_dir, "privacy.html")
    with open(privacy_path, "w", encoding="utf-8") as f:
        f.write(privacy)
    report["files_created"].append("privacy.html")
    
    # ── 7. Build report ──────────────────────────────────────
    report["status"] = "complete"
    report["photo_map"] = photo_map
    report_path = os.path.join(output_dir, "build_report.json")
    with open(report_path, "w", encoding="utf-8") as f:
        json.dump(report, f, ensure_ascii=False, indent=2)
    report["files_created"].append("build_report.json")
    
    logger.info(f"[LandingBuilder] Build complete: {len(report['files_created'])} files, "
                f"{report['photos_generated']} photos, {len(report['errors'])} errors")
    return report


def _generate_css(blueprint: dict, design_spec: dict) -> str:
    """Генерирует CSS файл"""
    c = design_spec.get("colors", {})
    t = design_spec.get("typography", {})
    s = design_spec.get("spacing", {})
    
    css = f"""/* Generated by ORION Landing Builder */
:root {{
  --primary: {c.get('primary_color', '#2563EB')};
  --accent: {c.get('accent_color', '#F59E0B')};
  --bg: {c.get('bg_color', '#FFFFFF')};
  --text: {c.get('text_color', '#1F2937')};
  --text-muted: {c.get('text_muted', '#6B7280')};
  --radius: {c.get('border_radius', '12px')};
  --shadow: {c.get('shadow', '0 4px 6px -1px rgba(0,0,0,0.1)')};
  --font: {c.get('font_family', "'Inter', sans-serif")};
  --font-heading: {c.get('font_heading', "'Inter', sans-serif")};
  --container-max: {s.get('container_max_width', '1200px')};
}}

* {{ margin: 0; padding: 0; box-sizing: border-box; }}

html {{ scroll-behavior: smooth; }}

body {{
  font-family: var(--font);
  color: var(--text);
  background: var(--bg);
  line-height: {t.get('line_height', '1.6')};
  font-size: {t.get('body_size', '1rem')};
}}

.container {{
  max-width: var(--container-max);
  margin: 0 auto;
  padding: {s.get('container_padding', '0 24px')};
}}

section {{
  padding: {s.get('section_padding', '80px 0')};
}}

section.alt-bg {{
  background: {'#F8FAFC' if c.get('visual_style') == 'light' else '#1E293B'};
}}

h1 {{ font-family: var(--font-heading); font-size: {t.get('h1_size', '3.5rem')}; font-weight: {t.get('h1_weight', '800')}; line-height: 1.2; }}
h2 {{ font-family: var(--font-heading); font-size: {t.get('h2_size', '2.5rem')}; font-weight: {t.get('h2_weight', '700')}; line-height: 1.3; margin-bottom: 1rem; }}
h3 {{ font-family: var(--font-heading); font-size: {t.get('h3_size', '1.5rem')}; font-weight: {t.get('h3_weight', '600')}; }}

.section-header {{
  text-align: center;
  margin-bottom: 48px;
}}
.section-header p {{
  color: var(--text-muted);
  font-size: 1.125rem;
  max-width: 600px;
  margin: 0 auto;
}}

/* Hero */
.hero {{
  min-height: 90vh;
  display: flex;
  align-items: center;
  position: relative;
  overflow: hidden;
}}
.hero-content {{
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 48px;
  align-items: center;
}}
.hero-text h1 {{ margin-bottom: 24px; }}
.hero-text p {{ font-size: 1.25rem; color: var(--text-muted); margin-bottom: 32px; }}
.hero-image img {{ width: 100%; border-radius: var(--radius); box-shadow: var(--shadow); }}

/* Buttons */
.btn {{
  display: inline-flex;
  align-items: center;
  gap: 8px;
  padding: 14px 32px;
  border-radius: var(--radius);
  font-weight: 600;
  font-size: 1rem;
  text-decoration: none;
  transition: all 0.3s ease;
  cursor: pointer;
  border: none;
}}
.btn-primary {{
  background: var(--primary);
  color: white;
}}
.btn-primary:hover {{
  opacity: 0.9;
  transform: translateY(-2px);
  box-shadow: 0 8px 25px rgba(0,0,0,0.15);
}}
.btn-outline {{
  border: 2px solid var(--primary);
  color: var(--primary);
  background: transparent;
}}

/* Cards Grid */
.cards-grid {{
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: {s.get('card_gap', '24px')};
}}
.card {{
  background: var(--bg);
  border-radius: var(--radius);
  padding: 32px;
  box-shadow: var(--shadow);
  transition: transform 0.3s ease;
}}
.card:hover {{
  transform: translateY(-4px);
}}
.card img {{
  width: 100%;
  border-radius: calc(var(--radius) - 4px);
  margin-bottom: 16px;
}}

/* Pricing */
.pricing-grid {{
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 24px;
  align-items: start;
}}
.pricing-card {{
  background: var(--bg);
  border-radius: var(--radius);
  padding: 40px 32px;
  box-shadow: var(--shadow);
  text-align: center;
  position: relative;
}}
.pricing-card.featured {{
  border: 2px solid var(--primary);
  transform: scale(1.05);
}}
.pricing-card .price {{
  font-size: 2.5rem;
  font-weight: 800;
  color: var(--primary);
  margin: 16px 0;
}}

/* Testimonials */
.testimonials-grid {{
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 24px;
}}
.testimonial {{
  background: var(--bg);
  border-radius: var(--radius);
  padding: 32px;
  box-shadow: var(--shadow);
}}
.testimonial-author {{
  display: flex;
  align-items: center;
  gap: 12px;
  margin-top: 16px;
}}
.testimonial-author img {{
  width: 48px;
  height: 48px;
  border-radius: 50%;
  object-fit: cover;
}}

/* FAQ Accordion */
.faq-list {{
  max-width: 800px;
  margin: 0 auto;
}}
.faq-item {{
  border-bottom: 1px solid {'#E5E7EB' if c.get('visual_style') == 'light' else '#334155'};
  padding: 20px 0;
}}
.faq-question {{
  display: flex;
  justify-content: space-between;
  align-items: center;
  cursor: pointer;
  font-weight: 600;
  font-size: 1.125rem;
}}
.faq-answer {{
  max-height: 0;
  overflow: hidden;
  transition: max-height 0.3s ease;
  color: var(--text-muted);
  padding-top: 0;
}}
.faq-item.active .faq-answer {{
  max-height: 500px;
  padding-top: 12px;
}}

/* Contact Form */
.contact-grid {{
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 48px;
}}
.form-group {{
  margin-bottom: 20px;
}}
.form-group label {{
  display: block;
  margin-bottom: 8px;
  font-weight: 500;
}}
.form-group input,
.form-group textarea {{
  width: 100%;
  padding: 12px 16px;
  border: 1px solid {'#D1D5DB' if c.get('visual_style') == 'light' else '#475569'};
  border-radius: var(--radius);
  font-family: var(--font);
  font-size: 1rem;
  background: {'#F9FAFB' if c.get('visual_style') == 'light' else '#1E293B'};
  color: var(--text);
  transition: border-color 0.3s;
}}
.form-group input:focus,
.form-group textarea:focus {{
  outline: none;
  border-color: var(--primary);
}}

/* CTA Banner */
.cta-banner {{
  background: linear-gradient(135deg, var(--primary), {'#1E40AF' if c.get('visual_style') == 'light' else '#1E3A5F'});
  color: white;
  text-align: center;
  padding: 80px 24px;
  border-radius: var(--radius);
}}
.cta-banner h2 {{ color: white; }}
.cta-banner p {{ color: rgba(255,255,255,0.9); margin-bottom: 32px; }}
.cta-banner .btn {{ background: white; color: var(--primary); }}

/* Footer */
footer {{
  background: {'#111827' if c.get('visual_style') == 'light' else '#020617'};
  color: {'#9CA3AF' if c.get('visual_style') == 'light' else '#64748B'};
  padding: 48px 0 24px;
}}
footer a {{ color: inherit; text-decoration: none; }}
footer a:hover {{ color: var(--primary); }}
.footer-grid {{
  display: grid;
  grid-template-columns: 2fr 1fr 1fr;
  gap: 48px;
  margin-bottom: 32px;
}}
.footer-bottom {{
  border-top: 1px solid {'#1F2937' if c.get('visual_style') == 'light' else '#1E293B'};
  padding-top: 24px;
  display: flex;
  justify-content: space-between;
  font-size: 0.875rem;
}}

/* Navbar */
.navbar {{
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  z-index: 1000;
  background: {'rgba(255,255,255,0.95)' if c.get('visual_style') == 'light' else 'rgba(15,23,42,0.95)'};
  backdrop-filter: blur(10px);
  box-shadow: 0 1px 3px rgba(0,0,0,0.1);
  transition: all 0.3s;
}}
.navbar .container {{
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding-top: 16px;
  padding-bottom: 16px;
}}
.nav-links {{
  display: flex;
  gap: 32px;
  list-style: none;
}}
.nav-links a {{
  color: var(--text);
  text-decoration: none;
  font-weight: 500;
  transition: color 0.3s;
}}
.nav-links a:hover {{ color: var(--primary); }}
.logo {{
  font-family: var(--font-heading);
  font-size: 1.5rem;
  font-weight: 800;
  color: var(--primary);
  text-decoration: none;
}}

/* Burger Menu */
.burger {{
  display: none;
  flex-direction: column;
  gap: 5px;
  cursor: pointer;
  background: none;
  border: none;
  padding: 4px;
}}
.burger span {{
  width: 24px;
  height: 2px;
  background: var(--text);
  transition: all 0.3s;
}}

/* Steps Timeline */
.steps {{
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
  gap: 32px;
  counter-reset: step;
}}
.step {{
  position: relative;
  padding-left: 60px;
}}
.step::before {{
  counter-increment: step;
  content: counter(step);
  position: absolute;
  left: 0;
  top: 0;
  width: 44px;
  height: 44px;
  background: var(--primary);
  color: white;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  font-weight: 700;
}}

/* Mobile */
@media (max-width: 768px) {{
  section {{ padding: {s.get('section_padding_mobile', '48px 0')}; }}
  h1 {{ font-size: 2rem; }}
  h2 {{ font-size: 1.75rem; }}
  .hero {{ min-height: auto; padding-top: 100px; }}
  .hero-content {{ grid-template-columns: 1fr; text-align: center; }}
  .hero-image {{ order: -1; }}
  .cards-grid,
  .pricing-grid,
  .testimonials-grid {{ grid-template-columns: 1fr; }}
  .contact-grid {{ grid-template-columns: 1fr; }}
  .footer-grid {{ grid-template-columns: 1fr; }}
  .nav-links {{ display: none; }}
  .nav-links.active {{
    display: flex;
    flex-direction: column;
    position: absolute;
    top: 100%;
    left: 0;
    right: 0;
    background: var(--bg);
    padding: 24px;
    box-shadow: var(--shadow);
  }}
  .burger {{ display: flex; }}
  .pricing-card.featured {{ transform: none; }}
}}
"""
    return css


def _generate_js(blueprint: dict) -> str:
    """Генерирует JavaScript файл"""
    has_faq = any(s["id"] == "faq" for s in blueprint.get("sections", []))
    has_form = bool(blueprint.get("forms"))
    
    js = """// Generated by ORION Landing Builder
document.addEventListener('DOMContentLoaded', function() {
  // ── Burger Menu ──────────────────────────────────────
  const burger = document.querySelector('.burger');
  const navLinks = document.querySelector('.nav-links');
  if (burger && navLinks) {
    burger.addEventListener('click', () => {
      navLinks.classList.toggle('active');
      burger.classList.toggle('active');
    });
    // Close on link click
    navLinks.querySelectorAll('a').forEach(link => {
      link.addEventListener('click', () => {
        navLinks.classList.remove('active');
        burger.classList.remove('active');
      });
    });
  }

  // ── Smooth Scroll ────────────────────────────────────
  document.querySelectorAll('a[href^="#"]').forEach(anchor => {
    anchor.addEventListener('click', function(e) {
      e.preventDefault();
      const target = document.querySelector(this.getAttribute('href'));
      if (target) {
        target.scrollIntoView({ behavior: 'smooth', block: 'start' });
      }
    });
  });

  // ── Navbar Scroll Effect ─────────────────────────────
  const navbar = document.querySelector('.navbar');
  if (navbar) {
    window.addEventListener('scroll', () => {
      if (window.scrollY > 50) {
        navbar.classList.add('scrolled');
      } else {
        navbar.classList.remove('scrolled');
      }
    });
  }

  // ── AOS Init ─────────────────────────────────────────
  if (typeof AOS !== 'undefined') {
    AOS.init({
      duration: 800,
      offset: 100,
      once: true,
    });
  }
"""
    
    if has_faq:
        js += """
  // ── FAQ Accordion ────────────────────────────────────
  document.querySelectorAll('.faq-question').forEach(q => {
    q.addEventListener('click', () => {
      const item = q.parentElement;
      const wasActive = item.classList.contains('active');
      document.querySelectorAll('.faq-item').forEach(i => i.classList.remove('active'));
      if (!wasActive) item.classList.add('active');
    });
  });
"""
    
    if has_form:
        js += """
  // ── Form Submit ──────────────────────────────────────
  document.querySelectorAll('form[data-ajax]').forEach(form => {
    form.addEventListener('submit', async function(e) {
      e.preventDefault();
      const btn = form.querySelector('button[type="submit"]');
      const origText = btn.textContent;
      btn.textContent = 'Отправка...';
      btn.disabled = true;
      
      try {
        const data = new FormData(form);
        const resp = await fetch(form.action, { method: 'POST', body: data });
        const result = await resp.json();
        
        if (result.success) {
          form.innerHTML = '<div class="success-message"><h3>Спасибо!</h3><p>Мы свяжемся с вами в ближайшее время.</p></div>';
        } else {
          btn.textContent = 'Ошибка. Попробуйте ещё раз';
          setTimeout(() => { btn.textContent = origText; btn.disabled = false; }, 3000);
        }
      } catch(err) {
        btn.textContent = origText;
        btn.disabled = false;
        alert('Ошибка отправки. Попробуйте позже.');
      }
    });
  });
"""
    
    js += """
  // ── Counter Animation ────────────────────────────────
  const counters = document.querySelectorAll('[data-count]');
  const observer = new IntersectionObserver(entries => {
    entries.forEach(entry => {
      if (entry.isIntersecting) {
        const el = entry.target;
        const target = parseInt(el.dataset.count);
        let current = 0;
        const step = Math.ceil(target / 50);
        const timer = setInterval(() => {
          current += step;
          if (current >= target) { current = target; clearInterval(timer); }
          el.textContent = current.toLocaleString();
        }, 30);
        observer.unobserve(el);
      }
    });
  }, { threshold: 0.5 });
  counters.forEach(c => observer.observe(c));
});
"""
    return js


def _generate_php_handler(blueprint: dict) -> str:
    """Генерирует PHP обработчик форм"""
    forms = blueprint.get("forms", [])
    fields = set()
    for form in forms:
        fields.update(form.get("fields", []))
    
    field_sanitize = ""
    field_body = ""
    for field in sorted(fields):
        label = {"name": "Имя", "phone": "Телефон", "email": "Email", "message": "Сообщение"}.get(field, field)
        field_sanitize += f"${field} = htmlspecialchars(trim($_POST['{field}'] ?? ''));\n    "
        field_body += f'$body .= "{label}: ${field}\\n";\n    '
    
    php = f"""<?php
header('Content-Type: application/json; charset=utf-8');
header('Access-Control-Allow-Origin: *');

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {{
    echo json_encode(['success' => false, 'error' => 'Method not allowed']);
    exit;
}}

// Sanitize
    {field_sanitize}

// Validate
if (empty($name) || (empty($phone) && empty($email))) {{
    echo json_encode(['success' => false, 'error' => 'Заполните обязательные поля']);
    exit;
}}

// Build email body
$body = "Новая заявка с сайта\\n\\n";
    {field_body}
$body .= "Дата: " . date('d.m.Y H:i') . "\\n";
$body .= "IP: " . $_SERVER['REMOTE_ADDR'] . "\\n";

// Send email
$to = 'admin@' . $_SERVER['HTTP_HOST'];
$subject = 'Новая заявка с сайта';
$headers = "From: noreply@" . $_SERVER['HTTP_HOST'] . "\\r\\n";
$headers .= "Content-Type: text/plain; charset=utf-8\\r\\n";

$sent = @mail($to, $subject, $body, $headers);

// Save to file as backup
$log = date('Y-m-d H:i:s') . ' | ' . str_replace("\\n", ' | ', trim($body)) . "\\n";
@file_put_contents(__DIR__ . '/leads.log', $log, FILE_APPEND | LOCK_EX);

echo json_encode(['success' => true, 'message' => 'Заявка отправлена']);
"""
    return php


def _generate_html(blueprint: dict, content: dict, design_spec: dict, photo_map: dict) -> str:
    """Генерирует HTML файл"""
    meta = blueprint.get("meta", {})
    nav = blueprint.get("navigation", [])
    sections = blueprint.get("sections", [])
    fonts = design_spec.get("google_fonts", ["Inter"])
    name = blueprint.get("name", "Site")
    
    fonts_url = "https://fonts.googleapis.com/css2?" + "&".join(
        [f"family={f.replace(' ', '+')}:wght@400;500;600;700;800" for f in fonts]
    ) + "&display=swap"
    
    # Build sections HTML
    sections_html = ""
    for i, section in enumerate(sections):
        section_content = content.get(section["id"], {})
        alt_class = " alt-bg" if i % 2 == 1 else ""
        aos = ' data-aos="fade-up"' if section.get("has_animation") else ""
        
        if section["id"] == "hero":
            sections_html += _render_hero(section, section_content, photo_map, name)
        elif section["type"] == "cards_grid":
            sections_html += _render_cards(section, section_content, photo_map, alt_class, aos)
        elif section["type"] == "pricing_cards":
            sections_html += _render_pricing(section, section_content, alt_class, aos)
        elif section["type"] == "testimonials_slider":
            sections_html += _render_testimonials(section, section_content, photo_map, alt_class, aos)
        elif section["type"] == "accordion":
            sections_html += _render_faq(section, section_content, alt_class, aos)
        elif section["type"] == "contact_form":
            sections_html += _render_contact(section, section_content, blueprint, alt_class, aos)
        elif section["type"] == "cta_banner":
            sections_html += _render_cta(section, section_content, aos)
        elif section["type"] == "steps_timeline":
            sections_html += _render_steps(section, section_content, alt_class, aos)
        elif section["type"] == "icons_grid":
            sections_html += _render_advantages(section, section_content, alt_class, aos)
        else:
            sections_html += _render_generic(section, section_content, photo_map, alt_class, aos)
    
    # Nav links
    nav_html = ""
    section_ids = {s["id"]: s for s in sections}
    for nav_item in nav:
        section_id = next((sid for sid, s in section_ids.items() 
                          if _section_nav_name_reverse(nav_item) == sid), "")
        if section_id:
            nav_html += f'        <li><a href="#{section_id}">{nav_item}</a></li>\n'
    
    # Footer
    footer_html = _render_footer(blueprint, nav)
    
    html = f"""<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{meta.get('title', name)}</title>
  <meta name="description" content="{meta.get('description', '')}">
  <meta property="og:title" content="{meta.get('title', name)}">
  <meta property="og:description" content="{meta.get('description', '')}">
  <meta property="og:type" content="website">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link href="{fonts_url}" rel="stylesheet">
  <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <!-- Navbar -->
  <nav class="navbar">
    <div class="container">
      <a href="#" class="logo">{name}</a>
      <ul class="nav-links">
{nav_html}      </ul>
      <button class="burger" aria-label="Menu">
        <span></span><span></span><span></span>
      </button>
    </div>
  </nav>

{sections_html}

{footer_html}

  <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
  <script src="main.js"></script>
</body>
</html>"""
    return html


def _render_hero(section, content, photo_map, name):
    img = _get_photo_tag(section["id"], photo_map)
    h1 = content.get("h1", section.get("h1", ""))
    subtitle = content.get("subtitle", section.get("subtitle", ""))
    cta = section.get("cta_text", "Получить консультацию")
    return f"""
  <!-- Hero -->
  <section class="hero" id="hero">
    <div class="container">
      <div class="hero-content">
        <div class="hero-text">
          <h1>{h1}</h1>
          <p>{subtitle}</p>
          <a href="#contacts" class="btn btn-primary">{cta}</a>
        </div>
        <div class="hero-image">
          {img}
        </div>
      </div>
    </div>
  </section>
"""


def _render_cards(section, content, photo_map, alt_class, aos):
    h2 = content.get("h1", section.get("h1", ""))
    subtitle = content.get("subtitle", section.get("subtitle", ""))
    items = content.get("items", [])
    cards_html = ""
    for item in items:
        cards_html += f"""
      <div class="card"{aos}>
        <h3>{item.get('title', '')}</h3>
        <p>{item.get('description', '')}</p>
      </div>"""
    return f"""
  <!-- {section['id']} -->
  <section id="{section['id']}" class="{alt_class}">
    <div class="container">
      <div class="section-header"{aos}>
        <h2>{h2}</h2>
        <p>{subtitle}</p>
      </div>
      <div class="cards-grid">
        {cards_html}
      </div>
    </div>
  </section>
"""


def _render_pricing(section, content, alt_class, aos):
    h2 = content.get("h1", section.get("h1", ""))
    plans = content.get("plans", [])
    cards = ""
    for i, plan in enumerate(plans):
        featured = " featured" if plan.get("featured") else ""
        features_html = "".join(f"<li>{f}</li>" for f in plan.get("features", []))
        cards += f"""
      <div class="pricing-card{featured}"{aos}>
        <h3>{plan.get('name', '')}</h3>
        <div class="price">{plan.get('price', '')}</div>
        <ul>{features_html}</ul>
        <a href="#contacts" class="btn btn-primary">{section.get('cta_text', 'Выбрать')}</a>
      </div>"""
    return f"""
  <section id="{section['id']}" class="{alt_class}">
    <div class="container">
      <div class="section-header"{aos}><h2>{h2}</h2></div>
      <div class="pricing-grid">{cards}</div>
    </div>
  </section>
"""


def _render_testimonials(section, content, photo_map, alt_class, aos):
    h2 = content.get("h1", section.get("h1", ""))
    reviews = content.get("reviews", [])
    cards = ""
    for r in reviews:
        cards += f"""
      <div class="testimonial"{aos}>
        <p>"{r.get('text', '')}"</p>
        <div class="testimonial-author">
          <div><strong>{r.get('name', '')}</strong><br><small>{r.get('role', '')}</small></div>
        </div>
      </div>"""
    return f"""
  <section id="{section['id']}" class="{alt_class}">
    <div class="container">
      <div class="section-header"{aos}><h2>{h2}</h2></div>
      <div class="testimonials-grid">{cards}</div>
    </div>
  </section>
"""


def _render_faq(section, content, alt_class, aos):
    h2 = content.get("h1", section.get("h1", ""))
    items = content.get("items", [])
    faq_html = ""
    for item in items:
        faq_html += f"""
      <div class="faq-item">
        <div class="faq-question">{item.get('question', '')}<span>+</span></div>
        <div class="faq-answer">{item.get('answer', '')}</div>
      </div>"""
    return f"""
  <section id="{section['id']}" class="{alt_class}">
    <div class="container">
      <div class="section-header"{aos}><h2>{h2}</h2></div>
      <div class="faq-list">{faq_html}</div>
    </div>
  </section>
"""


def _render_contact(section, content, blueprint, alt_class, aos):
    h2 = content.get("h1", section.get("h1", ""))
    forms = blueprint.get("forms", [])
    contact_form = next((f for f in forms if f.get("section") == "contacts"), {})
    fields = contact_form.get("fields", ["name", "phone", "email", "message"])
    
    field_labels = {"name": "Имя", "phone": "Телефон", "email": "Email", "message": "Сообщение"}
    field_types = {"name": "text", "phone": "tel", "email": "email", "message": "textarea"}
    
    fields_html = ""
    for field in fields:
        label = field_labels.get(field, field)
        ftype = field_types.get(field, "text")
        if ftype == "textarea":
            fields_html += f"""
        <div class="form-group">
          <label for="{field}">{label}</label>
          <textarea id="{field}" name="{field}" rows="4" placeholder="{label}"></textarea>
        </div>"""
        else:
            fields_html += f"""
        <div class="form-group">
          <label for="{field}">{label}</label>
          <input type="{ftype}" id="{field}" name="{field}" placeholder="{label}" required>
        </div>"""
    
    return f"""
  <section id="contacts" class="{alt_class}">
    <div class="container">
      <div class="section-header"{aos}><h2>{h2}</h2></div>
      <div class="contact-grid">
        <form action="send.php" method="POST" data-ajax{aos}>
          {fields_html}
          <button type="submit" class="btn btn-primary">{contact_form.get('submit_text', 'Отправить')}</button>
        </form>
        <div class="contact-info"{aos}>
          {content.get('info_html', '<p>Мы всегда на связи. Заполните форму и мы ответим в течение часа.</p>')}
        </div>
      </div>
    </div>
  </section>
"""


def _render_cta(section, content, aos):
    h2 = content.get("h1", section.get("h1", ""))
    subtitle = content.get("subtitle", section.get("subtitle", ""))
    cta = section.get("cta_text", "Начать")
    return f"""
  <section id="cta"{aos}>
    <div class="container">
      <div class="cta-banner">
        <h2>{h2}</h2>
        <p>{subtitle}</p>
        <a href="#contacts" class="btn">{cta}</a>
      </div>
    </div>
  </section>
"""


def _render_steps(section, content, alt_class, aos):
    h2 = content.get("h1", section.get("h1", ""))
    steps = content.get("steps", [])
    steps_html = ""
    for step in steps:
        steps_html += f"""
      <div class="step"{aos}>
        <h3>{step.get('title', '')}</h3>
        <p>{step.get('description', '')}</p>
      </div>"""
    return f"""
  <section id="{section['id']}" class="{alt_class}">
    <div class="container">
      <div class="section-header"{aos}><h2>{h2}</h2></div>
      <div class="steps">{steps_html}</div>
    </div>
  </section>
"""


def _render_advantages(section, content, alt_class, aos):
    h2 = content.get("h1", section.get("h1", ""))
    items = content.get("items", [])
    cards = ""
    for item in items:
        icon = item.get("icon", "star")
        cards += f"""
      <div class="card"{aos}>
        <div style="font-size:2rem;margin-bottom:12px;">{icon}</div>
        <h3>{item.get('title', '')}</h3>
        <p>{item.get('description', '')}</p>
      </div>"""
    return f"""
  <section id="{section['id']}" class="{alt_class}">
    <div class="container">
      <div class="section-header"{aos}><h2>{h2}</h2></div>
      <div class="cards-grid">{cards}</div>
    </div>
  </section>
"""


def _render_generic(section, content, photo_map, alt_class, aos):
    h2 = content.get("h1", section.get("h1", ""))
    text = content.get("text", "")
    img = _get_photo_tag(section["id"], photo_map) if section.get("photo_needed") else ""
    return f"""
  <section id="{section['id']}" class="{alt_class}">
    <div class="container"{aos}>
      <div class="section-header"><h2>{h2}</h2></div>
      <p>{text}</p>
      {img}
    </div>
  </section>
"""


def _render_footer(blueprint, nav):
    name = blueprint.get("name", "Site")
    footer = blueprint.get("footer", {})
    nav_html = "".join(f'<li><a href="#{_section_nav_name_reverse(n)}">{n}</a></li>' for n in nav)
    social = footer.get("social_links", [])
    social_html = " ".join(f'<a href="#">{s.title()}</a>' for s in social)
    
    return f"""
  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="footer-grid">
        <div>
          <a href="#" class="logo">{name}</a>
          <p style="margin-top:12px;">Профессиональные решения для вашего бизнеса</p>
        </div>
        <div>
          <h4>Навигация</h4>
          <ul style="list-style:none;margin-top:12px;">{nav_html}</ul>
        </div>
        <div>
          <h4>Соцсети</h4>
          <div style="margin-top:12px;display:flex;gap:16px;">{social_html}</div>
        </div>
      </div>
      <div class="footer-bottom">
        <span>&copy; {name} 2026. Все права защищены.</span>
        <a href="privacy.html">Политика конфиденциальности</a>
      </div>
    </div>
  </footer>
"""


def _generate_privacy_page(blueprint, design_spec):
    name = blueprint.get("name", "Site")
    fonts = design_spec.get("google_fonts", ["Inter"])
    fonts_url = "https://fonts.googleapis.com/css2?" + "&".join(
        [f"family={f.replace(' ', '+')}:wght@400;600;700" for f in fonts]
    ) + "&display=swap"
    
    return f"""<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Политика конфиденциальности — {name}</title>
  <link href="{fonts_url}" rel="stylesheet">
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <nav class="navbar"><div class="container"><a href="index.html" class="logo">{name}</a></div></nav>
  <section style="padding-top:120px;">
    <div class="container" style="max-width:800px;">
      <h1>Политика конфиденциальности</h1>
      <p>Дата обновления: 2026</p>
      <h2>1. Сбор информации</h2>
      <p>Мы собираем информацию, которую вы предоставляете через формы на сайте: имя, телефон, email.</p>
      <h2>2. Использование информации</h2>
      <p>Информация используется для обработки заявок и связи с вами.</p>
      <h2>3. Защита данных</h2>
      <p>Мы принимаем меры для защиты ваших персональных данных.</p>
      <h2>4. Cookies</h2>
      <p>Сайт может использовать cookies для улучшения работы.</p>
      <h2>5. Контакты</h2>
      <p>По вопросам обработки данных обращайтесь через форму на сайте.</p>
    </div>
  </section>
</body>
</html>"""


def _get_photo_tag(section_id, photo_map):
    for key, url in photo_map.items():
        if key.startswith(section_id):
            return f'<img src="images/{key}" alt="{section_id}" loading="lazy">'
    return f'<img src="images/{section_id}.png" alt="{section_id}" loading="lazy">'


def _section_nav_name_reverse(name):
    mapping = {
        "О нас": "about", "Услуги": "services", "Портфолио": "portfolio",
        "Тарифы": "pricing", "Отзывы": "reviews", "Команда": "team",
        "FAQ": "faq", "Контакты": "contacts", "Преимущества": "advantages",
        "Как мы работаем": "process", "Галерея": "gallery", "Партнёры": "partners", "Блог": "blog",
    }
    return mapping.get(name, name.lower())
