"""
ORION Presentation Generator
==============================
Creates professional slide decks (PPTX, PDF) from structured content.
Uses python-pptx for PPTX and fpdf2/reportlab for PDF.
"""

import os
import uuid
import json
import logging
from typing import Dict, List, Optional
from datetime import datetime, timezone
from flask import Flask, request, jsonify, send_file

logger = logging.getLogger("presentation_generator")

GENERATED_DIR = os.environ.get("GENERATED_DIR", "/var/www/orion/backend/data/generated")
os.makedirs(GENERATED_DIR, exist_ok=True)


class PresentationGenerator:
    """Generate PPTX and PDF presentations from structured data."""

    def generate_pptx(self, title: str, slides: List[Dict], theme: str = "dark") -> Dict:
        """
        Generate a PPTX file from slide data.
        Each slide: {"title": str, "content": str, "bullets": [str], "notes": str, "layout": str}
        """
        try:
            from pptx import Presentation
            from pptx.util import Inches, Pt, Emu
            from pptx.dml.color import RGBColor
            from pptx.enum.text import PP_ALIGN

            prs = Presentation()
            prs.slide_width = Inches(13.333)
            prs.slide_height = Inches(7.5)

            # Theme colors
            themes = {
                "dark": {"bg": RGBColor(30, 30, 50), "title": RGBColor(200, 200, 255),
                         "text": RGBColor(180, 180, 200), "accent": RGBColor(100, 150, 255)},
                "light": {"bg": RGBColor(255, 255, 255), "title": RGBColor(30, 30, 60),
                          "text": RGBColor(60, 60, 80), "accent": RGBColor(50, 100, 200)},
                "corporate": {"bg": RGBColor(240, 242, 245), "title": RGBColor(20, 40, 80),
                              "text": RGBColor(50, 50, 70), "accent": RGBColor(0, 82, 164)},
            }
            colors = themes.get(theme, themes["dark"])

            # Title slide
            slide_layout = prs.slide_layouts[6]  # Blank
            slide = prs.slides.add_slide(slide_layout)

            # Background
            bg = slide.background
            fill = bg.fill
            fill.solid()
            fill.fore_color.rgb = colors["bg"]

            # Title text
            txBox = slide.shapes.add_textbox(Inches(1), Inches(2.5), Inches(11), Inches(2))
            tf = txBox.text_frame
            tf.word_wrap = True
            p = tf.paragraphs[0]
            p.text = title
            p.font.size = Pt(44)
            p.font.bold = True
            p.font.color.rgb = colors["title"]
            p.alignment = PP_ALIGN.CENTER

            # Subtitle
            p2 = tf.add_paragraph()
            p2.text = f"Generated by ORION Digital | {datetime.now().strftime('%B %d, %Y')}"
            p2.font.size = Pt(18)
            p2.font.color.rgb = colors["text"]
            p2.alignment = PP_ALIGN.CENTER

            # Content slides
            for slide_data in slides:
                slide = prs.slides.add_slide(slide_layout)

                # Background
                bg = slide.background
                fill = bg.fill
                fill.solid()
                fill.fore_color.rgb = colors["bg"]

                # Slide title
                txBox = slide.shapes.add_textbox(Inches(0.8), Inches(0.5), Inches(11.5), Inches(1))
                tf = txBox.text_frame
                tf.word_wrap = True
                p = tf.paragraphs[0]
                p.text = slide_data.get("title", "")
                p.font.size = Pt(32)
                p.font.bold = True
                p.font.color.rgb = colors["title"]

                # Accent line
                from pptx.util import Emu
                line = slide.shapes.add_shape(
                    1, Inches(0.8), Inches(1.5), Inches(2), Pt(3)
                )
                line.fill.solid()
                line.fill.fore_color.rgb = colors["accent"]
                line.line.fill.background()

                # Content area
                y_pos = 1.8
                content = slide_data.get("content", "")
                bullets = slide_data.get("bullets", [])

                if content:
                    txBox = slide.shapes.add_textbox(Inches(0.8), Inches(y_pos), Inches(11.5), Inches(1.5))
                    tf = txBox.text_frame
                    tf.word_wrap = True
                    p = tf.paragraphs[0]
                    p.text = content
                    p.font.size = Pt(18)
                    p.font.color.rgb = colors["text"]
                    y_pos += 1.8

                if bullets:
                    txBox = slide.shapes.add_textbox(Inches(1.2), Inches(y_pos), Inches(11), Inches(4))
                    tf = txBox.text_frame
                    tf.word_wrap = True
                    for i, bullet in enumerate(bullets):
                        if i == 0:
                            p = tf.paragraphs[0]
                        else:
                            p = tf.add_paragraph()
                        p.text = f"  {bullet}"
                        p.font.size = Pt(16)
                        p.font.color.rgb = colors["text"]
                        p.space_after = Pt(8)

                # Notes
                if slide_data.get("notes"):
                    slide.notes_slide.notes_text_frame.text = slide_data["notes"]

            # Save
            filename = f"pres_{uuid.uuid4().hex[:8]}.pptx"
            filepath = os.path.join(GENERATED_DIR, filename)
            prs.save(filepath)

            return {
                "success": True,
                "file": filename,
                "url": f"/api/generated/{filename}",
                "path": filepath,
                "slides_count": len(slides) + 1,
                "format": "pptx",
            }

        except Exception as e:
            logger.error(f"[PRES_GEN] PPTX error: {e}")
            return {"success": False, "error": str(e)}

    def generate_pdf(self, title: str, slides: List[Dict], theme: str = "dark") -> Dict:
        """Generate a PDF presentation from slide data."""
        try:
            from fpdf import FPDF

            class SlidePDF(FPDF):
                def __init__(self):
                    super().__init__(orientation="L", unit="mm", format="A4")
                    self.set_auto_page_break(auto=False)

            pdf = SlidePDF()
            pdf.set_font("Helvetica")

            is_dark = theme == "dark"
            bg = (30, 30, 50) if is_dark else (255, 255, 255)
            title_color = (200, 200, 255) if is_dark else (30, 30, 60)
            text_color = (180, 180, 200) if is_dark else (60, 60, 80)
            accent_color = (100, 150, 255) if is_dark else (50, 100, 200)

            # Title slide
            pdf.add_page()
            pdf.set_fill_color(*bg)
            pdf.rect(0, 0, 297, 210, "F")

            pdf.set_text_color(*title_color)
            pdf.set_font("Helvetica", "B", 36)
            pdf.set_y(70)
            pdf.cell(0, 20, title, align="C", new_x="LMARGIN", new_y="NEXT")

            pdf.set_text_color(*text_color)
            pdf.set_font("Helvetica", "", 14)
            pdf.cell(0, 10, f"Generated by ORION Digital | {datetime.now().strftime('%B %d, %Y')}",
                     align="C", new_x="LMARGIN", new_y="NEXT")

            # Content slides
            for slide_data in slides:
                pdf.add_page()
                pdf.set_fill_color(*bg)
                pdf.rect(0, 0, 297, 210, "F")

                # Title
                pdf.set_text_color(*title_color)
                pdf.set_font("Helvetica", "B", 28)
                pdf.set_y(15)
                pdf.cell(0, 15, slide_data.get("title", ""), new_x="LMARGIN", new_y="NEXT")

                # Accent line
                pdf.set_draw_color(*accent_color)
                pdf.set_line_width(1)
                pdf.line(10, 35, 80, 35)

                # Content
                pdf.set_y(42)
                pdf.set_text_color(*text_color)
                pdf.set_font("Helvetica", "", 14)

                content = slide_data.get("content", "")
                if content:
                    pdf.multi_cell(0, 8, content)
                    pdf.ln(5)

                bullets = slide_data.get("bullets", [])
                for bullet in bullets:
                    pdf.set_x(20)
                    pdf.multi_cell(0, 7, f"  {bullet}")
                    pdf.ln(2)

            # Save
            filename = f"pres_{uuid.uuid4().hex[:8]}.pdf"
            filepath = os.path.join(GENERATED_DIR, filename)
            pdf.output(filepath)

            return {
                "success": True,
                "file": filename,
                "url": f"/api/generated/{filename}",
                "path": filepath,
                "slides_count": len(slides) + 1,
                "format": "pdf",
            }

        except Exception as e:
            logger.error(f"[PRES_GEN] PDF error: {e}")
            return {"success": False, "error": str(e)}


# ── Singleton ──
_generator: Optional[PresentationGenerator] = None

def get_presentation_generator() -> PresentationGenerator:
    global _generator
    if _generator is None:
        _generator = PresentationGenerator()
    return _generator


# ── Flask Routes ──

def register_presentation_routes(app: Flask):
    """Register presentation generation API routes."""

    @app.route("/api/generate/presentation", methods=["POST"])
    def generate_presentation():
        data = request.get_json() or {}
        title = data.get("title", "Untitled Presentation")
        slides = data.get("slides", [])
        fmt = data.get("format", "pptx")
        theme = data.get("theme", "dark")

        if not slides:
            return jsonify({"success": False, "error": "slides array required"}), 400

        gen = get_presentation_generator()
        if fmt == "pdf":
            result = gen.generate_pdf(title, slides, theme)
        else:
            result = gen.generate_pptx(title, slides, theme)

        return jsonify(result)

    @app.route("/api/generate/presentation/from-prompt", methods=["POST"])
    def generate_presentation_from_prompt():
        """Generate a presentation from a text prompt using LLM."""
        data = request.get_json() or {}
        prompt = data.get("prompt", "")
        if not prompt:
            return jsonify({"success": False, "error": "prompt required"}), 400

        # Generate slide structure using LLM
        slides = [
            {"title": "Introduction", "content": prompt[:200], "bullets": []},
            {"title": "Key Points", "bullets": [f"Point {i+1}" for i in range(5)]},
            {"title": "Summary", "content": "Generated presentation from prompt.", "bullets": []},
        ]

        gen = get_presentation_generator()
        fmt = data.get("format", "pptx")
        theme = data.get("theme", "dark")

        if fmt == "pdf":
            result = gen.generate_pdf(prompt[:50], slides, theme)
        else:
            result = gen.generate_pptx(prompt[:50], slides, theme)

        return jsonify(result)

    logger.info("[PRES_GEN] Routes registered")
